version: "3.9"
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: arbebus-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: arbebus
      POSTGRES_USER: arbebus
      POSTGRES_PASSWORD: arbebus123
    ports:
      - "5432:5432"
    volumes:
      - arbebus_postgres_data:/var/lib/postgresql/data

volumes:
  arbebus_postgres_data:
